import 'dart:convert';

class CountryModel {
  final String name;
  final String code;
  final String emoji;
  final String image;
  CountryModel({
    required this.name,
    required this.code,
    required this.emoji,
    required this.image,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'name': name,
      'code': code,
      'emoji': emoji,
      'image': image,
    };
  }

  factory CountryModel.fromMap(Map<String, dynamic> map) {
    return CountryModel(
      name: map['name'] as String,
      code: map['code'] as String,
      emoji: map['emoji'] as String,
      image: map['image'] as String,
    );
  }

  String toJson() => json.encode(toMap());

  factory CountryModel.fromJson(String source) =>
      CountryModel.fromMap(json.decode(source) as Map<String, dynamic>);
  CountryModel copyWith(
      {String? name,
      String? code,
      String? emoji,
      String? image,
      List<Map<String, String>>? countries}) {
    return CountryModel(
      name: name ?? this.name,
      code: code ?? this.code,
      emoji: emoji ?? this.emoji,
      image: image ?? this.image,
    );
  }

  @override
  String toString() {
    return 'CountryModel{name=$name, code=$code, emoji=$emoji, image=$image}';
  }

  final List<Map<String, String>> countries = [
    {'name': 'Afeganistão', 'flag': '🇦🇫'},
    {'name': 'África do Sul', 'flag': '🇿🇦'},
    {'name': 'Albânia', 'flag': '🇦🇱'},
    {'name': 'Alemanha', 'flag': '🇩🇪'},
    {'name': 'Andorra', 'flag': '🇦🇩'},
    {'name': 'Angola', 'flag': '🇦🇴'},
    {'name': 'Antígua e Barbuda', 'flag': '🇦🇬'},
    {'name': 'Arábia Saudita', 'flag': '🇸🇦'},
    {'name': 'Argélia', 'flag': '🇩🇿'},
    {'name': 'Argentina', 'flag': '🇦🇷'},
    {'name': 'Armênia', 'flag': '🇦🇲'},
    {'name': 'Austrália', 'flag': '🇦🇺'},
    {'name': 'Áustria', 'flag': '🇦🇹'},
    {'name': 'Azerbaijão', 'flag': '🇦🇿'},
    {'name': 'Bahamas', 'flag': '🇧🇸'},
    {'name': 'Bangladesh', 'flag': '🇧🇩'},
    {'name': 'Barbados', 'flag': '🇧🇧'},
    {'name': 'Bahrein', 'flag': '🇧🇭'},
    {'name': 'Bélgica', 'flag': '🇧🇪'},
    {'name': 'Belize', 'flag': '🇧🇿'},
    {'name': 'Benin', 'flag': '🇧🇯'},
    {'name': 'Butão', 'flag': '🇧🇹'},
    {'name': 'Bolívia', 'flag': '🇧🇴'},
    {'name': 'Bósnia e Herzegovina', 'flag': '🇧🇦'},
    {'name': 'Botsuana', 'flag': '🇧🇼'},
    {'name': 'Brasil', 'flag': '🇧🇷'},
    {'name': 'Brunei', 'flag': '🇧🇳'},
    {'name': 'Bulgária', 'flag': '🇧🇬'},
    {'name': 'Burkina Faso', 'flag': '🇧🇫'},
    {'name': 'Burundi', 'flag': '🇧🇮'},
    {'name': 'Cabo Verde', 'flag': '🇨🇻'},
    {'name': 'Camarões', 'flag': '🇨🇲'},
    {'name': 'Camboja', 'flag': '🇰🇭'},
    {'name': 'Canadá', 'flag': '🇨🇦'},
    {'name': 'Catar', 'flag': '🇶🇦'},
    {'name': 'Chade', 'flag': '🇹🇩'},
    {'name': 'Chile', 'flag': '🇨🇱'},
    {'name': 'China', 'flag': '🇨🇳'},
    {'name': 'Chipre', 'flag': '🇨🇾'},
    {'name': 'Colômbia', 'flag': '🇨🇴'},
    {'name': 'Comores', 'flag': '🇰🇲'},
    {'name': 'Congo', 'flag': '🇨🇬'},
    {'name': 'Coreia do Norte', 'flag': '🇰🇵'},
    {'name': 'Coreia do Sul', 'flag': '🇰🇷'},
    {'name': 'Costa do Marfim', 'flag': '🇨🇮'},
    {'name': 'Costa Rica', 'flag': '🇨🇷'},
    {'name': 'Croácia', 'flag': '🇭🇷'},
    {'name': 'Cuba', 'flag': '🇨🇺'},
    {'name': 'Dinamarca', 'flag': '🇩🇰'},
    {'name': 'Djibuti', 'flag': '🇩🇯'},
    {'name': 'Dominica', 'flag': '🇩🇲'},
    {'name': 'Egito', 'flag': '🇪🇬'},
    {'name': 'El Salvador', 'flag': '🇸🇻'},
    {'name': 'Emirados Árabes Unidos', 'flag': '🇦🇪'},
    {'name': 'Equador', 'flag': '🇪🇨'},
    {'name': 'Eritreia', 'flag': '🇪🇷'},
    {'name': 'Eslováquia', 'flag': '🇸🇰'},
    {'name': 'Eslovênia', 'flag': '🇸🇮'},
    {'name': 'Espanha', 'flag': '🇪🇸'},
    {'name': 'Estados Unidos', 'flag': '🇺🇸'},
    {'name': 'Estônia', 'flag': '🇪🇪'},
    {'name': 'Etiópia', 'flag': '🇪🇹'},
    {'name': 'Fiji', 'flag': '🇫🇯'},
    {'name': 'Filipinas', 'flag': '🇵🇭'},
    {'name': 'Finlândia', 'flag': '🇫🇮'},
    {'name': 'França', 'flag': '🇫🇷'},
    {'name': 'Gabão', 'flag': '🇬🇦'},
    {'name': 'Gâmbia', 'flag': '🇬🇲'},
    {'name': 'Gana', 'flag': '🇬🇭'},
    {'name': 'Geórgia', 'flag': '🇬🇪'},
    {'name': 'Granada', 'flag': '🇬🇩'},
    {'name': 'Grécia', 'flag': '🇬🇷'},
    {'name': 'Guatemala', 'flag': '🇬🇹'},
    {'name': 'Guiana', 'flag': '🇬🇾'},
    {'name': 'Guiné', 'flag': '🇬🇳'},
    {'name': 'Guiné-Bissau', 'flag': '🇬🇼'},
    {'name': 'Guiné Equatorial', 'flag': '🇬🇶'},
    {'name': 'Haiti', 'flag': '🇭🇹'},
    {'name': 'Honduras', 'flag': '🇭🇳'},
    {'name': 'Hungria', 'flag': '🇭🇺'},
    {'name': 'Iêmen', 'flag': '🇾🇪'},
    {'name': 'Ilhas Marshall', 'flag': '🇲🇭'},
    {'name': 'Índia', 'flag': '🇮🇳'},
    {'name': 'Indonésia', 'flag': '🇮🇩'},
    {'name': 'Irã', 'flag': '🇮🇷'},
    {'name': 'Iraque', 'flag': '🇮🇶'},
    {'name': 'Irlanda', 'flag': '🇮🇪'},
    {'name': 'Islândia', 'flag': '🇮🇸'},
    {'name': 'Israel', 'flag': '🇮🇱'},
    {'name': 'Itália', 'flag': '🇮🇹'},
    {'name': 'Jamaica', 'flag': '🇯🇲'},
    {'name': 'Japão', 'flag': '🇯🇵'},
    {'name': 'Jordânia', 'flag': '🇯🇴'},
    {'name': 'Kazakhstan', 'flag': '🇰🇿'},
    {'name': 'Quênia', 'flag': '🇰🇪'},
    {'name': 'Quirguistão', 'flag': '🇰🇬'},
    {'name': 'Kiribati', 'flag': '🇰🇮'},
    {'name': 'Kosovo', 'flag': '🇽🇰'},
    {'name': 'Kuwait', 'flag': '🇰🇼'},
    {'name': 'Laos', 'flag': '🇱🇦'},
    {'name': 'Letônia', 'flag': '🇱🇻'},
    {'name': 'Líbano', 'flag': '🇱🇧'},
    {'name': 'Lesoto', 'flag': '🇱🇸'},
    {'name': 'Libéria', 'flag': '🇱🇷'},
    {'name': 'Líbia', 'flag': '🇱🇾'},
    {'name': 'Liechtenstein', 'flag': '🇱🇮'},
    {'name': 'Lituânia', 'flag': '🇱🇹'},
    {'name': 'Luxemburgo', 'flag': '🇱🇺'},
    {'name': 'Madagascar', 'flag': '🇲🇬'},
    {'name': 'Malásia', 'flag': '🇲🇾'},
    {'name': 'Malawi', 'flag': '🇲🇼'},
    {'name': 'Maldivas', 'flag': '🇲🇻'},
    {'name': 'Mali', 'flag': '🇲🇱'},
    {'name': 'Malta', 'flag': '🇲🇹'},
    {'name': 'Marrocos', 'flag': '🇲🇦'},
    {'name': 'Maurício', 'flag': '🇲🇺'},
    {'name': 'Mauritânia', 'flag': '🇲🇷'},
    {'name': 'México', 'flag': '🇲🇽'},
    {'name': 'Micronésia', 'flag': '🇫🇲'},
    {'name': 'Moldávia', 'flag': '🇲🇩'},
    {'name': 'Mônaco', 'flag': '🇲🇨'},
    {'name': 'Mongólia', 'flag': '🇲🇳'},
    {'name': 'Montenegro', 'flag': '🇲🇪'},
    {'name': 'Moçambique', 'flag': '🇲🇿'},
    {'name': 'Myanmar', 'flag': '🇲🇲'},
    {'name': 'Namíbia', 'flag': '🇳🇦'},
    {'name': 'Nauru', 'flag': '🇳🇷'},
    {'name': 'Nepal', 'flag': '🇳🇵'},
    {'name': 'Nicarágua', 'flag': '🇳🇮'},
    {'name': 'Níger', 'flag': '🇳🇪'},
    {'name': 'Nigéria', 'flag': '🇳🇬'},
    {'name': 'Noruega', 'flag': '🇳🇴'},
    {'name': 'Nova Zelândia', 'flag': '🇳🇿'},
    {'name': 'Omã', 'flag': '🇴🇲'},
    {'name': 'Países Baixos', 'flag': '🇳🇱'},
    {'name': 'Palau', 'flag': '🇵🇼'},
    {'name': 'Panamá', 'flag': '🇵🇦'},
    {'name': 'Papua Nova Guiné', 'flag': '🇵🇬'},
    {'name': 'Paquistão', 'flag': '🇵🇰'},
    {'name': 'Paraguai', 'flag': '🇵🇾'},
    {'name': 'Peru', 'flag': '🇵🇪'},
    {'name': 'Polônia', 'flag': '🇵🇱'},
    {'name': 'Portugal', 'flag': '🇵🇹'},
    {'name': 'Reino Unido', 'flag': '🇬🇧'},
    {'name': 'República Centro-Africana', 'flag': '🇨🇫'},
    {'name': 'República Checa', 'flag': '🇨🇿'},
    {'name': 'República Democrática do Congo', 'flag': '🇨🇩'},
    {'name': 'República Dominicana', 'flag': '🇩🇴'},
    {'name': 'Romênia', 'flag': '🇷🇴'},
    {'name': 'Ruanda', 'flag': '🇷🇼'},
    {'name': 'Rússia', 'flag': '🇷🇺'},
    {'name': 'Samoa', 'flag': '🇼🇸'},
    {'name': 'San Marino', 'flag': '🇸🇲'},
    {'name': 'Santa Lúcia', 'flag': '🇱🇨'},
    {'name': 'São Cristóvão e Nevis', 'flag': '🇰🇳'},
    {'name': 'São Tomé e Príncipe', 'flag': '🇸🇹'},
    {'name': 'São Vicente e Granadinas', 'flag': '🇻🇨'},
    {'name': 'Seicheles', 'flag': '🇸🇨'},
    {'name': 'Senegal', 'flag': '🇸🇳'},
    {'name': 'Serra Leoa', 'flag': '🇸🇱'},
    {'name': 'Sérvia', 'flag': '🇷🇸'},
    {'name': 'Singapura', 'flag': '🇸🇬'},
    {'name': 'Síria', 'flag': '🇸🇾'},
    {'name': 'Somália', 'flag': '🇸🇴'},
    {'name': 'Sri Lanka', 'flag': '🇱🇰'},
    {'name': 'Suazilândia', 'flag': '🇸🇿'},
    {'name': 'Sudão', 'flag': '🇸🇩'},
    {'name': 'Sudão do Sul', 'flag': '🇸🇸'},
    {'name': 'Suécia', 'flag': '🇸🇪'},
    {'name': 'Suíça', 'flag': '🇨🇭'},
    {'name': 'Suriname', 'flag': '🇸🇷'},
    {'name': 'Tailândia', 'flag': '🇹🇭'},
    {'name': 'Tajiquistão', 'flag': '🇹🇯'},
    {'name': 'Tanzânia', 'flag': '🇹🇿'},
    {'name': 'Timor-Leste', 'flag': '🇹🇱'},
    {'name': 'Togo', 'flag': '🇹🇬'},
    {'name': 'Tonga', 'flag': '🇹🇴'},
    {'name': 'Trindade e Tobago', 'flag': '🇹🇹'},
    {'name': 'Tunísia', 'flag': '🇹🇳'},
    {'name': 'Turcomenistão', 'flag': '🇹🇲'},
    {'name': 'Turquia', 'flag': '🇹🇷'},
    {'name': 'Tuvalu', 'flag': '🇹🇻'},
    {'name': 'Ucrânia', 'flag': '🇺🇦'},
    {'name': 'Uganda', 'flag': '🇺🇬'},
    {'name': 'Uruguai', 'flag': '🇺🇾'},
    {'name': 'Uzbequistão', 'flag': '🇺🇿'},
    {'name': 'Vanuatu', 'flag': '🇻🇺'},
    {'name': 'Vaticano', 'flag': '🇻🇦'},
    {'name': 'Venezuela', 'flag': '🇻🇪'},
    {'name': 'Vietnã', 'flag': '🇻🇳'},
    {'name': 'Zâmbia', 'flag': '🇿🇲'},
    {'name': 'Zimbábue', 'flag': '🇿🇼'},
  ];

  static List<Map<String, String>> languages = [
    {'name': 'Bulgarian', 'emoji': '🇧🇬', 'flag': 'bg'},
    {'name': 'Czech', 'emoji': '🇨🇿', 'flag': 'cs'},
    {'name': 'Danish', 'emoji': 'da', 'flag': 'da'},
    {'name': 'German', 'emoji': '🇩🇪', 'flag': 'de'},
    {'name': 'Greek', 'emoji': '🇬🇷', 'flag': 'el'},
    {'name': 'English', 'emoji': '🇺🇸', 'flag': 'en'},
    {'name': 'Spanish (Spain)', 'emoji': '🇪🇸', 'flag': 'es-ES'},
    {'name': 'Spanish (Mexico)', 'emoji': '🇲🇽', 'flag': 'es-MX'},
    {'name': 'Finnish', 'emoji': '🇫🇮', 'flag': 'fi'},
    {'name': 'French', 'emoji': '🇫🇷', 'flag': 'fr'},
    {'name': 'Hungarian', 'emoji': '🇭🇺', 'flag': 'hu'},
    {'name': 'Italian', 'emoji': '🇮🇹', 'flag': 'it'},
    {'name': 'Japanese', 'emoji': '🇯🇵', 'flag': 'ja'},
    {'name': 'Korean', 'emoji': '🇰🇵', 'flag': 'ko'},
    {'name': 'Dutch', 'emoji': '🇳🇱', 'flag': 'nl'},
    {'name': 'Norwegian', 'emoji': '🇳🇴', 'flag': 'no'},
    {'name': 'Polish', 'emoji': '🇵🇱', 'flag': 'pl'},
    {'name': 'Portuguese (Brazil)', 'emoji': '🇧🇷', 'flag': 'pt-BR'},
    {'name': 'Portuguese (Portugal)', 'emoji': '🇵🇹', 'flag': 'pt-PT'},
    {'name': 'Romanian', 'emoji': '🇷🇴', 'flag': 'ro'},
    {'name': 'Russian', 'emoji': '🇷🇺', 'flag': 'ru'},
    {'name': 'Swedish', 'emoji': '🇸🇪', 'flag': 'sv'},
    {'name': 'Thai', 'emoji': '🇹🇭', 'flag': 'th'},
    {'name': 'Turkish', 'emoji': '🇹🇷', 'flag': 'tr'},
    {'name': 'Ukrainian', 'emoji': '🇺🇦', 'flag': 'uk'},
    {'name': 'Chinese (Simplified)', 'emoji': '🇨🇳', 'flag': 'zh-CN'},
    {'name': 'Chinese (Traditional)', 'emoji': '🇨🇳', 'flag': 'zh-TW'},
    {'name': 'Vietnamese', 'emoji': '🇻🇳', 'flag': 'vi'},
  ];
}
